# Generated by Django 4.2.6 on 2023-10-28 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fancy_dress', models.ImageField(blank=True, null=True, upload_to='user_uploads/fancy_dress')),
                ('drawing', models.ImageField(blank=True, null=True, upload_to='user_uploads/drawing')),
                ('essay_writing', models.ImageField(blank=True, null=True, upload_to='user_uploads/essay_writing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
