# Generated by Django 4.2.6 on 2023-10-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_userimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimages',
            name='user',
        ),
        migrations.AddField(
            model_name='userimages',
            name='user_record',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.userrecord'),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
