# Generated by Django 4.2.6 on 2023-10-29 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_remove_userimages_user_userimages_user_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='user_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
