# Generated by Django 4.2.6 on 2023-11-03 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadedimages_alter_userrecord_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimages',
            name='image',
        ),
    ]
