# Generated by Django 4.2.6 on 2023-11-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userimages_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimages',
            old_name='user_record',
            new_name='Email_id',
        ),
    ]
