# Generated by Django 4.2.6 on 2023-11-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_user_record_userimages_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimages',
            old_name='Email_id',
            new_name='user_record',
        ),
    ]
