# Generated by Django 4.2.6 on 2023-11-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_email_id_userimages_user_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImages',
        ),
        migrations.AlterField(
            model_name='userimages',
            name='user_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userrecord'),
        ),
    ]
